language: node_js
node_js:
    - "6"
    - "8"
    - "9"
dist: trusty # needs Ubuntu Trusty
sudo: required
addons:
  chrome: stable # have Travis install chrome stable.
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test
