name: Build on Linux

on: [push]

env:
  NODE_OPTIONS: --max-old-space-size=2048

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: ['18', '20', '21']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        yarn --no-lockfile
        yarn prepare

    - name: Run linter
      run: yarn lint
    
    - name: Run tests
      run: yarn test
